name: mgr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - astropy
  - dvc
  - dvc-gdrive
  - flake8
  - ipykernel
  - numpy
  - pandas
  - pyarrow
  - plotly
  - pydantic
  - pytest
  - scikit-learn
  - seaborn
  - tqdm
  - pip
  - pip:
    - black[jupyter]
    - PyAstronomy[occult]
