name: mgr
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - astropy
  - beautifulsoup4
  - dvc
  - dvc-gdrive
  - flake8
  - ipykernel
  - numpy
  - cupy
  - pandas
  - pyarrow
  - plotly
  - pydantic
  - pytest
  - scikit-learn
  - pytorch
  - pytorch-cuda==12.1
  - seaborn
  - tqdm
  - pip
  - pip:
    - black[jupyter]
    - lightkurve
