name: mgr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flake8
  - ipykernel
  - numpy
  - seaborn
  - pandas
  - scikit-learn
  - plotly
  - pytest
  - tqdm
  - pip
  - pip:
    - black[jupyter]