name: mgr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - astropy
  - dvc
  - dvc-gdrive
  - flake8
  - ipykernel
  - numpy
  - pandas
  - plotly
  - pydantic
  - pytest
  - scikit-learn
  - seaborn
  - tqdm
  - pip
  - pip:
    - black[jupyter]
